---
version: '3.4'

services:

  web:
    build:
      context: src
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DATABASE_URL=postgresql://admin:admin_pw@database/admin
      - FEEDBACK_EMAIL=office-hours-devs@umich.edu
    ports:
      - 8003:8001
    volumes:
      - ./src:/usr/src/app:z
    command: "python -m uvicorn officehours.asgi:application --host=0.0.0.0 --port=8001 --reload"
    depends_on:
      - database
      - redis
      - webpack_watcher

  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=admin_pw
    volumes:
      - officehours-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7

  webpack_watcher:
    build:
      context: src
      target: node-webpack
    command: npm run watch
    volumes:
      - ./src:/usr/src/app:z
      - /usr/src/app/node_modules/

volumes:
  officehours-postgres-data:
