---

services:

  web:
    build:
      context: src
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DATABASE_URL=postgresql://admin:admin_pw@database/admin
      - FEEDBACK_EMAIL=office-hours-devs@umich.edu
    ports:
      - 8003:8001
      - 5678:5678
    volumes:
      - ./src:/usr/src/app:z
    command: >
      python -m debugpy --listen 0.0.0.0:5678 --wait-for-client
      -m uvicorn officehours.asgi:application --host=0.0.0.0 --port=8001 --reload
    depends_on:
      - database
      - redis
      - webpack_watcher

  database:
    image: postgres:14.7-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=admin_pw
    volumes:
      - officehours-postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:7
    command: redis-server --stop-writes-on-bgsave-error no --save ""
    # This is to simulate an Openshift container with no write permission except to /tmp
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - officehours-redis-ro:/data:ro

  webpack_watcher:
    build:
      context: src
      target: node-webpack
    command: npm run watch
    volumes:
      - ./src:/usr/src/app:z
      - /usr/src/app/node_modules/

volumes:
  officehours-postgres-data:
  officehours-redis-ro:
