---
version: '3.4'

services:

  web:
    build:
      context: src
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DATABASE_URL=postgresql://admin:admin@database/postgres
      - FEEDBACK_EMAIL=office-hours-devs@umich.edu
    ports:
      - 8003:8001
    volumes:
      - ./src:/usr/src/app:z
    command: "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - database
      - redis
      - webpack_watcher

  database:
    image: postgres:10.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
    volumes:
      - officehours-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:5

  webpack_watcher:
    build:
      context: src
      target: node-webpack
    command: npm run watch
    volumes:
      - ./src:/usr/src/app:z
      - /usr/src/app/node_modules/

volumes:
  officehours-postgres-data:
