apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- redis-deployment.yaml
- redis-service.yaml
- web-deployment.yaml
- web-autoscaler.yaml
- web-service.yaml
- web-ingress.yaml
- build.yaml
- imagestream.yaml
labels:
- includeSelectors: true
  pairs:
    org: umich
    project: officehours
namePrefix: officehours-
secretGenerator:
- files:
  - secret/ALLOWED_HOSTS
  - secret/DEBUG
  - secret/SECRET_KEY
  - secret/DATABASE_URL
  - secret/OIDC_RP_CLIENT_ID
  - secret/OIDC_RP_CLIENT_SECRET
  - secret/OIDC_OP_AUTHORIZATION_ENDPOINT
  - secret/OIDC_OP_TOKEN_ENDPOINT
  - secret/OIDC_OP_USER_ENDPOINT
  - secret/OIDC_OP_JWKS_ENDPOINT
  - secret/OIDC_CREATE_USER
  - secret/FEEDBACK_EMAIL
  - secret/ADMIN_EMAIL
  - secret/EMAIL_HOST
  - secret/GA_TRACKING_ID
  - secret/ONE_TRUST_SCRIPT_DOMAIN
  - secret/REDIS_HOST
  - secret/TWILIO_ACCOUNT_SID
  - secret/TWILIO_AUTH_TOKEN
  - secret/TWILIO_MESSAGING_SERVICE_SID
  - secret/ZOOM_SIGN_IN_HELP
  name: secrets
  type: Opaque
- files:
  - secret/WebHookSecretKey
  name: github
  type: Opaque
crds:
- openshift-buildconfig.json
- openshift-deploymentconfig.json
